const converters = [
  {
    id: 1,
    label: "Area",
    value: "area",
    units: [
      { unit: "kilometre" },
      { unit: "Meter" },
      { unit: "Centimetre" },
      { unit: "micrometres" },
      { unit: "Nanometre" },
      { unit: "Mile" },
      { unit: "Yard" },
      { unit: "Foot" },
      { unit: "Inch" },
      { unit: "Nautical mile" },
    ],
  },
  {
    id: 2,
    label: "Data Transfer Rate",
    value: "dataTransferRate",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 3,
    label: "Digital Storage",
    value: "digitalStorage",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 4,
    label: "Energy",
    value: "energy",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 5,
    label: "Frequency",
    value: "frequency",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 6,
    label: "Fuel Economy",
    value: "fuelEconomy",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 7,
    label: "Length",
    value: "length",
    units: [
      { unit: "kilometre" },
      { unit: "Meter" },
      { unit: "Centimetre" },
      { unit: "micrometres" },
      { unit: "Nanometre" },
      { unit: "Mile" },
      { unit: "Yard" },
      { unit: "Foot" },
      { unit: "Inch" },
      { unit: "Nautical mile" },
    ],
  },
  {
    id: 8,
    label: "Mass",
    value: "mass",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 9,
    label: "Plane Angle",
    value: "planeAngle",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 10,
    label: "Pressure",
    value: "pressure",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 11,
    label: "Speed",
    value: "speed",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 12,
    label: "Temperature",
    value: "temperature",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 13,
    label: "Time",
    value: "time",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
  {
    id: 14,
    label: "Volume",
    value: "volume",
    units: [
      { unit: "kilometre1" },
      { unit: "Meter1" },
      { unit: "Centimetre1" },
      { unit: "micrometres1" },
      { unit: "Nanometr1e" },
      { unit: "Mile1" },
      { unit: "Yard1" },
      { unit: "Foot1" },
      { unit: "Inch1" },
      { unit: "Nautical mile1" },
    ],
  },
];

export default converters;
